### ISSUE TITLE
Solving an Error in procedure to build the base images

### ISSUE THREAD

**Issue by patrickfleith** [HPI-Information-Systems/TimeEval-algorithms#11]
Hi, I would like to report on an issue I encounter by following the steps to prepare the docker base images (step 1 in the README).
I run the following:

- change to the `0-base-images` folder: cd `0-base-images`
- build your desired base image, e.g. `docker build -t registry.gitlab.hpi.de/akita/i/python3-base:0.2.5 ./python3-base` --> **sucess**
- (optionally: build derived base image, e.g. `docker build -t registry.gitlab.hpi.de/akita/i/pyod:0.2.5 ./pyod)` --> **failed**

_=> The way I solved it was to modify the pyod Dockerfile._

Maybe this information could be added to the README file. Otherwise this issue may be useful to someone in the future.

Originally the Dockerfile looks like:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/64135237/210248587-ce4e06a7-d317-48cf-ba01-d4eaa53085c1.png">

After the modification it looks like:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/64135237/210248671-68f20d69-0bb3-4176-9b28-a7dd21272b30.png">

**Comment by CodeLionX** [comment]
Hi Patrick,

Thank you for your feedback. We actually received multiple help requests regarding this step. So, our documentation wasn't precise enough there.

I included an additional step in the README to re-tag the base image as `:latest` in addition to `:0.2.5` (ded806d). This also fixes your reported error. We think that this is a better solution than changing the Dockerfiles of the derived base images because it does not break our internal build pipeline and keeps the difference between this public mirror and our internal repository smaller.

**Comment by patrickfleith** [comment]
Excellent, that's great !
