### ISSUE TITLE
img embedding cae - time series scoring not averaged

### ISSUE THREAD

**Issue by janthmueller** [HPI-Information-Systems/TimeEval-algorithms#5]
Hello, 

as part of my master's thesis, i am working on the topic of anomaly detection and time series imaging. In the context of my thesis, I would like to take up your results and have a question regarding the time series scoring of the img-embedding-cae. 

Your paper states that overlapping scores are averaged, which is presumably the case with this reconstruction model with a window stride of 1. However, this is not apparent to me within your [code](https://github.com/HPI-Information-Systems/TimeEval-algorithms/blob/main/img_embedding_cae/algorithm.py). 

I would be very happy if you could help me further as I am very interested in using your metric as a basis of comparison for my research.

**Comment by CodeLionX** [comment]
Dear @janthmueller,

Thank you for your interest in our work.

Yes, if we have overlapping window scores, we take the average score over all windows for each point of the original time series. However, ImageEmbeddingCAE – in our implementation – uses tumbling windows and has no overlap between the windows. We decided for tumbling windows because the authors of the paper also describe this in Section 4.2:

> [...] we split the time series of length 61 440 into 120 slices of size $l_1$ equal to 512. No additional operations such as smoothing or normalization is performed.

▶️ $\frac{61440}{512} = 120 \to \text{slide} = \text{window size}$

You can see this in our implementation in two places. When creating the time series subsequences (windows):

https://github.com/HPI-Information-Systems/TimeEval-algorithms/blob/92d7e1b4be55d204174efd6705ee100c0acd8e80/img_embedding_cae/img_embedding_cae/dataset.py#L18-L19

And when calculating the anomaly scoring (we just repeat the window score $window size$ times to convert it to the point scores):

https://github.com/HPI-Information-Systems/TimeEval-algorithms/blob/92d7e1b4be55d204174efd6705ee100c0acd8e80/img_embedding_cae/algorithm.py#L65-L68

**Comment by janthmueller** [comment]
Hello @CodeLionX,

thank you very much for the detailed answer. At the current time I have copied all docker images to a private gitlab container registry following these steps and I noticed the following: 
- renamed registry paths in docker files via py script (i don't have access to gitlab hpi).
- automatically build multiple images of algorithms and their dependent base images (via py script)
- Noticed: There are dockerfiles inside the folder 0-base-images where actual image tags were not used (like pyod or timeeval-test-algorithm). Is this intentional or has it been forgotten?

After downloading the provided datasets I also wondered if all the data mentioned in the paper was used for each algorithm. How, for example, a dataset labeled as "unsupervised" could also be used for "semi-sumpervised" algorithms. Because in this case a holdout would probably have to happen, since the "unsupervised" labeled preprocessed (TimeEval format) datasets only contain test datasets according to my review.
Furthermore, the preprocessing documentation of the datasets in TimeEval format is still missing.

In this context I would be very happy if it would be possible for you to share not only the configurations of the algorithms but also the exact configuration of the datasets regarding the used algorithms (like preprocessing or holdout etc). Furthermore, it would be nice if you could additionally share the code responsible for transferring datasets that are not allowed to be shared (such as WebscopeS5) into the TimeEval format.

**Comment by CodeLionX** [comment]
I labeled your questions for easier reference:

**A**: Yes, that's correct and intentional. We use an internal CI to build all the Docker images and the base image build script ensures that the intermediate images, such as _pyod_ or _timeeval-test-algorithm_, are built directly after the base images are built. They, therefore, always refer to the _latest_-tag. There are technical reason why we cannot fix the tags to correct version-numbers atm.
If you need the version numbers, just fork or pull this repository and add them to the Dockerfiles.

---

**B**: That's a fine observation and the reason both algorithms and datasets must have `input_dimensionality` and `training_type` metadata assigned to them. TimeEval will handle the matching of datasets to algorithms. You can read about it [here](https://timeeval.readthedocs.io/en/latest/concepts/configuration.html#avoiding-conflicting-combinations). In our evaluation, we used the TimeEval default configuration, which means the following:

For different learning types:

- unsupervised algorithms are executed on all datasets
- semi-supervised algorithms are executed on semi-supervised datasets only
- supervised algorithms are executed on supervised datasets only

For different input dimensionality:

- multivariate algorithms are executed on all datasets
- univariate algorithms are executed on univariate datasets only

---

**C**: Yes, unfortunately, we did not find the time to describe it on our website. However, the scripts (Jupyter notebooks) are available in the TimeEval-repository: [`notebooks/data-prep`](https://github.com/HPI-Information-Systems/TimeEval/tree/main/notebooks/data-prep). Kindly note that some notebooks are old and use an outdated TimeEval API. The necessary preprocessing steps are still the same, though.

---

**D**: See the preprocessing notebooks linked in C, e.g., [`notebooks/data-prep/YahooWebscopeS5.ipynb`](https://github.com/HPI-Information-Systems/TimeEval/blob/main/notebooks/data-prep/YahooWebscopeS5.ipynb) for _WebscopeS5_.

**Comment by janthmueller** [comment]
Thank you very much, this helps me a lot! I am looking forward to further work with your tools and hope that I can contribute other interesting algorithms later.
